name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_USER: axth
          MYSQL_PASSWORD: pwd
          MYSQL_DATABASE: axth
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

#      - name: Verify MariaDB connection
#        env:
#          PORT: ${{ job.services.mariadb.ports[3306] }}
#        run: |
#          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT"; do
#            sleep 1
#          done

      - name: Test
        run: go test -v ./...